version: "3.8"

services:
  app:
    container_name: task-crud-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      jaeger:   # ✅ tergantung Jaeger agar tracing langsung bisa kirim
        condition: service_started
    env_file:
      - .env
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  db:
    container_name: postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis-server
    image: redis:7
    command: [ "redis-server", "--port", "6380", "--requirepass", "secret123" ]
    ports:
      - "6380:6380"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.49
    container_name: jaeger
    ports:
      - "16686:16686"   # UI
      - "6831:6831/udp" # UDP tracing dari app Go
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
