# ---------- Stage 1: Build ----------
    FROM golang:1.23-alpine AS builder

    WORKDIR /app
    
    COPY go.mod go.sum ./
    RUN go mod tidy
    
    COPY . .
    
    RUN go build -o main ./main.go
    
    # ---------- Stage 2: Runtime ----------
    FROM alpine:latest
    
    WORKDIR /app
    
    COPY --from=builder /app/main .
    
    EXPOSE 8080
    
    CMD ["./main"]
    